sudo: required

dist: trusty

language: node_js

node_js:
  - 6
  - 7

branches:
  only: master

install: npm install

script: npm run test-cov

after_success: npm run send-cov

notifications:
  email:
    on_success: never
